### ISSUE TITLE
Experiencing Data Channel MediaHandler error after upgrading to 0.7.0

### ISSUE THREAD

**Issue by hattmarris** [onsip/SIP.js#175]
Wondering if you guys had encountered this error in the MediaHandler function for file / data transfer?

We're using the mediaHandlerFactory in the DataUA configuration object from the full app demo http://sipjs.com/guides/full-demo-app/

when loading 0.7.0, we're seeing - 
Uncaught TypeError: onSuccess.bind is not a function

![screenshot from 2015-05-20 13 27 14](https://cloud.githubusercontent.com/assets/8269432/7735794/5917f8b2-fef4-11e4-9555-917ad922bf54.png)

![screenshot from 2015-05-20 13 28 01](https://cloud.githubusercontent.com/assets/8269432/7735923/45b7564a-fef5-11e4-8bb0-1e1c42a1864d.png)

**Comment by joseph-onsip** [comment]
Thanks for pointing this out. It was a subtle change that slipped my mind. I'll have to update the demo and documentation, but here's the gist of things:

Version 0.7.0 changes the [MediaHandler](https://github.com/onsip/SIP.js/commit/85ef34686ef463996d1cf81748981f65f4870b11) and [MediaStreamManager](https://github.com/onsip/SIP.js/commit/baa693e3b866d81f6e517f10c216f267eb0135d9#diff-e1399654c69ffc39504bfe23e2bf8596) interfaces to use Promises instead of callbacks. It tries to be  backward-compatible by patching callback-oriented custom implementations of MediaStreamManager (e3f7af6e316eb58da143891d1a7cb44fb8b0731d), but the particular implementation in the demo does not get patched since it defines `acquire` as having only one argument.

Here's an updated [demo](http://jsfiddle.net/xv00uLur/103/) using version 0.7.0 with a Promise-oriented `MediaHandler` and `MediaStreamManager`. The section of code in question needed to be changed to:

```javascript
            /* Like a default mediaHandler, but no streams to manage */
            var self = new SIP.WebRTC.MediaHandler(session, {
                mediaStreamManager: {
                    acquire: function (mediaHint) {
                        return SIP.Utils.Promise.resolve([]);
                    },
                    release: function (stream) {
                        // no-op
                    }
                }
            });

            return self;
```

Also note that `self.addStream` is no longer overridden. [It was changed to `addStreams`](https://github.com/onsip/SIP.js/commit/502184cc4221c1953a4610ae87e1c9f187f82465), which behaves correctly when there are no streams in the array returned by `MediaStreamManager#acquire`.

**Comment by hattmarris** [comment]
No problem, and thank you Joseph - I will give 0.7.0 another spin today.  much appreciated - !

Matt

**Comment by joseph-onsip** [comment]
Sure thing, let us know if run into any more bugs!
