### ISSUE TITLE
Type 'unknown' on 'data' Attributes leads to Problems

### ISSUE THREAD

**Issue by Kasalehlia** [onsip/SIP.js#837]
Since upgrading this library from 0.15 the type of several `data` attributes has been changed to `unknown`, e.g.
https://github.com/onsip/SIP.js/blob/53d3307f3b6f449e94a699fa92e74e74753524e3/src/api/session.ts#L70

To properly use that attribute, type `any` was correct to prevent errors like
`TS2339: Property 'active' does not exist on type 'unknown'.`

Now, one would have to 'cast' every access with `(session.data as any).active`.

What is the rationale behind this change?

**Comment by john-e-riordan** [comment]
We are working toward removing `any` from the entire project. There's a handful more to go, but we're getting there.

Using the `any` type defeats the purpose of using TypeScript. When `any` is used, all compiler type checks around that value are ignored.

`unknown` is the type-safe counterpart of `any`. Anything is assignable to `unknown`, but `unknown` isn’t assignable to anything but itself and `any` (without control flow based narrowing or a type assertion). Likewise, no operations are permitted on an `unknown` without first narrowing to a more specific type or asserting.

The safe and recommended way to narrow the `unknown` type to a more specific type is to use the `typeof` operator, the `instanceof` operator, or custom type guard function. If you want to force the compiler to trust you that a value of type `unknown` is of a given type, you can use a type assertion ("cast").
