### ISSUE TITLE
SIP.WebRTC.isSupported() doesn't work in 0.8+

### ISSUE THREAD

**Issue by johnmorenov** [onsip/SIP.js#455]
I used to use SIP.WebRTC.isSupported() to detect if browser could support WebRTC, with 0.7 version, but now with the new version (0.8) I get this error:

**TypeError: SIP.WebRTC.isSupported is not a function**

Please help me, thanks.

**Comment by egreenmachine** [comment]
We have removed `SIP.WebRTC.isSupported()` from our library. It is up to the end user application to determine if it is running in an environment that can support it's features or not. SIP.js does not require WebRTC to work. It is fully capable of being a SIP stack where there is no WebRTC support.
